### PR TITLE
Fixed ts_utils.get_node_text deprecation

### PR DESCRIPTION
**Pull request by ItsSunnyMonster**

### CODE REVIEW

**Comment by Badhi** [comment]
Hi @ItsSunnyMonster,
I've been needing to remove this deprecation notice for a while but didn't have time. Thanks for taking it up. But I've noticed that some of the unit tests are failing. Could you please take a look at it as well? Otherwise, I'll check on it on my free time

**Comment by ItsSunnyMonster** [comment]
Hi, 

I looked over the unit tests and it seems like the failing test cases were `def_constructor`, `destructor` and `copy_constructor`. In all 3 of these cases, it fails because the `return_node` passed into `get_node_text` is `nil` (at line 158 in my fork and 148 in this repo). That does make sense since constructors and destructors don't have return types. 

I don't fully understand how Neovim plugins work, but my guess is that the old function handled the case where `node` is nil slightly differently from how the new function handles it? What was the return value of the old function when `node` is nil? I could perhaps add a check for nil and return this value in my wrapper around the new function.

**Comment by ItsSunnyMonster** [comment]
Alright, I found the implementation of the old function online and it turns out it simply returns an empty table if `node` is nil. I have added that to my branch and if that was correct all the unit tests should pass.

**Review by Badhi — APPROVED** [review]

**Comment by Badhi** [comment]
Thanks for help and the fix

**Pull request merged**
